---
- name: my first playbook
  hosts: webservers
  become: true
  tasks:

    - name: install docker
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: install pip3
      apt:
        name: python3-pip
        state: present

    - name: install docker pip
      pip:
        name: docker
        state: present


    - name: install dvwa container
      docker_container:
